export enum LIGNE_TYPE {
    DEPLACEMENT = "DEPLACEMENT",
    REPAS = "REPAS",
    LOGEMENT = "LOGEMENT",
    EVENEMENT_PROFESSIONNEL = "EVENEMENT PROFESSIONNEL",
    AUTRE = "AUTRE"
}

export enum NOTEDEFRAIS_ETAT {
    EN_ATTENTE_DE_VALIDATION = "EN_ATTENTE_DE_VALIDATION",
    BROUILLON = "BROUILLON",
    VALIDEE = "VALIDEE",
    REFUSEE = "REFUSEE"
}